channels:
- conda-forge
dependencies:
- python=3.11
- pyiron_base=0.8.0
- qe=7.2
- qe-tools=2.0.0
- ase=3.22.1
- matplotlib=3.8.3
- xmlschema=3.3.1
- jobflow=0.1.17
- pymatgen=2024.3.1
- aiida-core=2.5.1
- aiida-core.services
