name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.11"
        environment-file: book/environment.yml
        auto-activate-base: false
    - name: Install Jupyterbook
      shell: bash -l {0}
      run: |
        cp book/_config.yml .
        cp book/_toc.yml .
        cp book/*.md . 
        cp -r book/images .
        jupyter-book build . --path-output public
    - run: mv public/_build/html public_html
    - run: touch public_html/.nojekyll
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: public_html # The folder the action should deploy.
        CLEAN: true
